### ISSUE TITLE
Can't run python manage.py runserver

### ISSUE THREAD

**Issue by Wijantra** [EJEunjiyaz/django-polls#1]
### When i run server at \django-polls\mysite\ using command "python manage.py runserver", it doesn't work because of 2 line.

**1.line 24 in django-polls/mysite/mysite/settings.py** 

> https://github.com/EJEunjiyaz/django-polls/blob/9cba4d857eba5da782793252cda0d85f81afe415/mysite/mysite/settings.py#L24

It shows this error message

> decouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.

You can define a default in line 24 or you can give a sample .env file for others to make their .env file.  

> SECRET_KEY = config('SECRET_KEY', default="secret")

**2.line 26 in django-polls/mysite/mysite/settings.py** 

> https://github.com/EJEunjiyaz/django-polls/blob/9cba4d857eba5da782793252cda0d85f81afe415/mysite/mysite/settings.py#L26

 It shows this error message

> decouple.UndefinedValueError: DEBUG not found. Declare it as envvar or define a default value.

You can define a default in line 26 or you can give a sample .env file for others to make their .env file. 

> DEBUG = config('DEBUG', cast = bool, default=True)

**Comment by EJEunjiyaz** [comment]
I already add .env file to the master branch, May you try and check does it work again? Thank you.

**Comment by Wijantra** [comment]
I think you shouldn't add .env file on git because .env file is in .gitignore.
Maybe you should try to add default in line 24 and 26 or tell others to make their .env file.

**Comment by EJEunjiyaz** [comment]
Completed
Line 24:
`SECRET_KEY = ...`

Line 26:
`DEBUG = config('DEBUG', cast=bool, default=True)`

Final check please.
Thank you for your advice.
