### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by Wijantra** [EJEunjiyaz/django-polls#2]
### In How to Run section
Maybe you should tell others to clone your repository first then migrate with this command **python manage.py migrate**

### Unnecessary requirements

This line in Requirements section is in requirements.txt so you don't repeat it.

> Django 2.1.2 or newer

**Comment by EJEunjiyaz** [comment]
Just change the whole of readme.

Please check again for the last proof.
Thank you Wijantra.
